#ifndef CARTPOLE_CONFIG_H
#define CARTPOLE_CONFIG_H

/* Scheduler and communication. */
#define CARTPOLE_CONTROL_PERIOD_MS 5U
#define CARTPOLE_MS_TO_SAMPLES(ms) ((ms) / CARTPOLE_CONTROL_PERIOD_MS)
/* Rates are differenced across this many frames (20 ms at 5 ms period). */
#define CARTPOLE_RATE_WINDOW_SAMPLES 4U
#define CARTPOLE_LED_TOGGLE_SAMPLES CARTPOLE_MS_TO_SAMPLES(200U)
#define CARTPOLE_OLED_PERIOD_MS 80U
#define CARTPOLE_COMMAND_TIMEOUT_MS 250U
#define CARTPOLE_PI_F 3.1415926f
#define CARTPOLE_ANGLE_ADC_AVERAGE_SAMPLES 10U

/* One-button calibration. */
#define CARTPOLE_AUTO_CAL_REQUIRED_SAMPLES CARTPOLE_MS_TO_SAMPLES(500U)
#define CARTPOLE_AUTO_CAL_TIMEOUT_SAMPLES CARTPOLE_MS_TO_SAMPLES(5000U)
#define CARTPOLE_AUTO_CAL_MAX_CONSECUTIVE_REJECTS 5U
#define CARTPOLE_ANGLE_ZERO_DEFAULT_ADC 1024.0f
#define CARTPOLE_ADC_TO_RAD (2.0f * CARTPOLE_PI_F / 4096.0f)
#define CARTPOLE_POT_ZERO_STRICT_WINDOW 1U
#define CARTPOLE_POT_ZERO_MIN_ADC 990U
#define CARTPOLE_POT_ZERO_MAX_ADC 1060U

/* Upright capture hysteresis. */
/* The pot's electrical span is less than 360 deg: with the zero taken at the
 * hanging position, the true upright reads ~0.127 rad past pi. First estimated
 * from the minimum-speed point of free rotations (logs/run1.csv), then refined
 * from the mean balanced angle, which also parked the cart ~0.06 m off centre
 * (logs/run2.csv). */
#define CARTPOLE_UPRIGHT_OFFSET_RAD 0.127f
#define CARTPOLE_UPRIGHT_ANGLE_RAD (CARTPOLE_PI_F + CARTPOLE_UPRIGHT_OFFSET_RAD)
#define CARTPOLE_CAPTURE_ENTER_ANGLE_RAD 0.30f
#define CARTPOLE_CAPTURE_EXIT_ANGLE_RAD 0.45f
#define CARTPOLE_CAPTURE_ENTER_RATE_RAD_S 3.5f
#define CARTPOLE_CAPTURE_EXIT_RATE_RAD_S 7.0f
/* LQR only recovers without running off the rail when the angle predicted
 * LEAD_S ahead (theta + LEAD_S * theta_dot) is small. */
#define CARTPOLE_CAPTURE_LEAD_S 0.20f
#define CARTPOLE_CAPTURE_ENTER_PREDICT_RAD 0.25f
#define CARTPOLE_CAPTURE_ENTER_SAMPLES CARTPOLE_MS_TO_SAMPLES(10U)
#define CARTPOLE_CAPTURE_EXIT_SAMPLES CARTPOLE_MS_TO_SAMPLES(20U)

/* Cart encoder and rail geometry. */
#define CARTPOLE_ENCODER_RIGHT_WALL_TICKS 0
#define CARTPOLE_ENCODER_LEFT_WALL_TICKS 4130
#define CARTPOLE_RAIL_MARGIN_TICKS 120
#define CARTPOLE_ENCODER_TRAVEL_TICKS \
  (CARTPOLE_ENCODER_LEFT_WALL_TICKS - CARTPOLE_ENCODER_RIGHT_WALL_TICKS)
#define CARTPOLE_ENCODER_HALF_TRAVEL_TICKS (CARTPOLE_ENCODER_TRAVEL_TICKS / 2)
#define CARTPOLE_ENCODER_METERS_PER_TICK \
  ((0.036f * CARTPOLE_PI_F) / 1040.0f)

/* Energy-shaping swing-up. */
#define CARTPOLE_SWINGUP_MAX_U (6900.0f / 7199.0f)
#define CARTPOLE_SWINGUP_PHASE_HYST_RAD_S 0.45f
#define CARTPOLE_SWINGUP_SUPPLY_VOLTAGE 12.0f
#define CARTPOLE_SWINGUP_WINDOW_HALF_TICKS 1700
#define CARTPOLE_SWINGUP_RETURN_EXIT_HALF_TICKS 1100
#define CARTPOLE_SWINGUP_RETURN_MAX_U (6900.0f / 7199.0f)
#define CARTPOLE_SWINGUP_RETURN_MIN_U 0.80f
#define CARTPOLE_SWINGUP_RETURN_K_X 0.00020f
#define CARTPOLE_SWINGUP_RETURN_K_V 0.00180f

/* 40 cm LQR ported from the supplied Wheeltec reference firmware. */
#define CARTPOLE_LQR_K_X (-36.4232f)
#define CARTPOLE_LQR_K_DX (-40.0996f)
#define CARTPOLE_LQR_K_THETA (-101.4914f)
#define CARTPOLE_LQR_K_DTHETA (-15.8376f)
#define CARTPOLE_LQR_SUPPLY_VOLTAGE 12.0f
#define CARTPOLE_LQR_MAX_U (6900.0f / 7199.0f)

/* Actuation, homing and local controls. */
/* Swing-up keeps the 22.5 /s rate that was tuned at 20 ms. */
#define CARTPOLE_SWINGUP_SLEW_PER_SAMPLE 0.1125f
#define CARTPOLE_BALANCE_SLEW_PER_SAMPLE 0.10f
#define CARTPOLE_JOG_U 0.18f
#define CARTPOLE_HOMING_MAX_U 0.58f
#define CARTPOLE_HOMING_MIN_U 0.14f
#define CARTPOLE_HOMING_DECAY_TICKS 1500.0f
#define CARTPOLE_MOTOR_DEADZONE_FORWARD_PWM 80U
#define CARTPOLE_MOTOR_DEADZONE_REVERSE_PWM 80U
#define CARTPOLE_RESERVED_KEY_LONG_PRESS_SAMPLES CARTPOLE_MS_TO_SAMPLES(1200U)

#endif /* CARTPOLE_CONFIG_H */
